org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -Dorg.gradle.warning.mode=none
android.useAndroidX=true
# Enable parallel builds & build caching for maximum compilation speed
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
